package com.ecommerce.mapper;

import com.ecommerce.entity.UserAuth;
import com.ecommerce.entity.UserAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    long countByExample(UserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    int deleteByExample(UserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    int deleteByPrimaryKey(Long userauthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    int insert(UserAuth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    int insertSelective(UserAuth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    List<UserAuth> selectByExampleWithBLOBs(UserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    List<UserAuth> selectByExample(UserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    UserAuth selectByPrimaryKey(Long userauthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    int updateByExampleSelective(@Param("row") UserAuth row, @Param("example") UserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") UserAuth row, @Param("example") UserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    int updateByExample(@Param("row") UserAuth row, @Param("example") UserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    int updateByPrimaryKeySelective(UserAuth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    int updateByPrimaryKeyWithBLOBs(UserAuth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    int updateByPrimaryKey(UserAuth row);
}