package com.ecommerce.mapper;

import com.ecommerce.entity.User;
import com.ecommerce.entity.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:12:26 HKT 2025
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:12:26 HKT 2025
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:12:26 HKT 2025
     */
    int deleteByPrimaryKey(Long userauthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:12:26 HKT 2025
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:12:26 HKT 2025
     */
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:12:26 HKT 2025
     */
    List<User> selectByExampleWithBLOBs(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:12:26 HKT 2025
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:12:26 HKT 2025
     */
    User selectByPrimaryKey(Long userauthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:12:26 HKT 2025
     */
    int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:12:26 HKT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:12:26 HKT 2025
     */
    int updateByExample(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:12:26 HKT 2025
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:12:26 HKT 2025
     */
    int updateByPrimaryKeyWithBLOBs(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:12:26 HKT 2025
     */
    int updateByPrimaryKey(User row);
}