spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 975314
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
server:
  servlet:
    session:
      timeout: 1800  # Session timeout in seconds (30 mins)
      cookie:
        name: JSESSIONID
#        http-only: true    # XSS protection
#        secure: true       # HTTPS only in production
        same-site: lax     # CSRF protection
  port: 8080
