package com.ecommerce.entity;

import java.io.Serializable;
import java.util.Date;

public class UserAuth implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userauth.USERAUTH_ID
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    private Long userauthId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userauth.USERAUTH_USERID
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    private Long userauthUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userauth.USERAUTH_AUTHTYPE
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    private Integer userauthAuthtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userauth.USERAUTH_IDENTIFIER
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    private String userauthIdentifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userauth.USERAUTH_PASSWORD
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    private String userauthPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userauth.USERAUTH_CREATED_AT
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    private Date userauthCreatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userauth.USERAUTH_UPADTED_AT
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    private Date userauthUpadtedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userauth.USERAUTH_TOKEN
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    private String userauthToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userauth.USERAUTH_ID
     *
     * @return the value of userauth.USERAUTH_ID
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public Long getUserauthId() {
        return userauthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userauth.USERAUTH_ID
     *
     * @param userauthId the value for userauth.USERAUTH_ID
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public void setUserauthId(Long userauthId) {
        this.userauthId = userauthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userauth.USERAUTH_USERID
     *
     * @return the value of userauth.USERAUTH_USERID
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public Long getUserauthUserid() {
        return userauthUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userauth.USERAUTH_USERID
     *
     * @param userauthUserid the value for userauth.USERAUTH_USERID
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public void setUserauthUserid(Long userauthUserid) {
        this.userauthUserid = userauthUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userauth.USERAUTH_AUTHTYPE
     *
     * @return the value of userauth.USERAUTH_AUTHTYPE
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public Integer getUserauthAuthtype() {
        return userauthAuthtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userauth.USERAUTH_AUTHTYPE
     *
     * @param userauthAuthtype the value for userauth.USERAUTH_AUTHTYPE
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public void setUserauthAuthtype(Integer userauthAuthtype) {
        this.userauthAuthtype = userauthAuthtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userauth.USERAUTH_IDENTIFIER
     *
     * @return the value of userauth.USERAUTH_IDENTIFIER
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public String getUserauthIdentifier() {
        return userauthIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userauth.USERAUTH_IDENTIFIER
     *
     * @param userauthIdentifier the value for userauth.USERAUTH_IDENTIFIER
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public void setUserauthIdentifier(String userauthIdentifier) {
        this.userauthIdentifier = userauthIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userauth.USERAUTH_PASSWORD
     *
     * @return the value of userauth.USERAUTH_PASSWORD
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public String getUserauthPassword() {
        return userauthPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userauth.USERAUTH_PASSWORD
     *
     * @param userauthPassword the value for userauth.USERAUTH_PASSWORD
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public void setUserauthPassword(String userauthPassword) {
        this.userauthPassword = userauthPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userauth.USERAUTH_CREATED_AT
     *
     * @return the value of userauth.USERAUTH_CREATED_AT
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public Date getUserauthCreatedAt() {
        return userauthCreatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userauth.USERAUTH_CREATED_AT
     *
     * @param userauthCreatedAt the value for userauth.USERAUTH_CREATED_AT
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public void setUserauthCreatedAt(Date userauthCreatedAt) {
        this.userauthCreatedAt = userauthCreatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userauth.USERAUTH_UPADTED_AT
     *
     * @return the value of userauth.USERAUTH_UPADTED_AT
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public Date getUserauthUpadtedAt() {
        return userauthUpadtedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userauth.USERAUTH_UPADTED_AT
     *
     * @param userauthUpadtedAt the value for userauth.USERAUTH_UPADTED_AT
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public void setUserauthUpadtedAt(Date userauthUpadtedAt) {
        this.userauthUpadtedAt = userauthUpadtedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userauth.USERAUTH_TOKEN
     *
     * @return the value of userauth.USERAUTH_TOKEN
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public String getUserauthToken() {
        return userauthToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userauth.USERAUTH_TOKEN
     *
     * @param userauthToken the value for userauth.USERAUTH_TOKEN
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    public void setUserauthToken(String userauthToken) {
        this.userauthToken = userauthToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauth
     *
     * @mbg.generated Sat Jul 26 08:54:56 HKT 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userauthId=").append(userauthId);
        sb.append(", userauthUserid=").append(userauthUserid);
        sb.append(", userauthAuthtype=").append(userauthAuthtype);
        sb.append(", userauthIdentifier=").append(userauthIdentifier);
        sb.append(", userauthPassword=").append(userauthPassword);
        sb.append(", userauthCreatedAt=").append(userauthCreatedAt);
        sb.append(", userauthUpadtedAt=").append(userauthUpadtedAt);
        sb.append(", userauthToken=").append(userauthToken);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}