package com.ecommerce.entity;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_ID
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_NAME
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_EMAIL
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_EMAIL_VERIFIED
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    private Boolean userEmailVerified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_PHONE_NUMBER
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    private String userPhoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_PHONE_VERIFIED
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    private Boolean userPhoneVerified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_CREATED_AT
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    private Date userCreatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_UPDATED_AT
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    private Date userUpdatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_UPDATED_BY
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    private Date userUpdatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_LAST_LOGIN_AT
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    private Date userLastLoginAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_ACTIVE
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    private Boolean userActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_ID
     *
     * @return the value of user.USER_ID
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_ID
     *
     * @param userId the value for user.USER_ID
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_NAME
     *
     * @return the value of user.USER_NAME
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_NAME
     *
     * @param userName the value for user.USER_NAME
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_EMAIL
     *
     * @return the value of user.USER_EMAIL
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_EMAIL
     *
     * @param userEmail the value for user.USER_EMAIL
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_EMAIL_VERIFIED
     *
     * @return the value of user.USER_EMAIL_VERIFIED
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public Boolean getUserEmailVerified() {
        return userEmailVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_EMAIL_VERIFIED
     *
     * @param userEmailVerified the value for user.USER_EMAIL_VERIFIED
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public void setUserEmailVerified(Boolean userEmailVerified) {
        this.userEmailVerified = userEmailVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_PHONE_NUMBER
     *
     * @return the value of user.USER_PHONE_NUMBER
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public String getUserPhoneNumber() {
        return userPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_PHONE_NUMBER
     *
     * @param userPhoneNumber the value for user.USER_PHONE_NUMBER
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public void setUserPhoneNumber(String userPhoneNumber) {
        this.userPhoneNumber = userPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_PHONE_VERIFIED
     *
     * @return the value of user.USER_PHONE_VERIFIED
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public Boolean getUserPhoneVerified() {
        return userPhoneVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_PHONE_VERIFIED
     *
     * @param userPhoneVerified the value for user.USER_PHONE_VERIFIED
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public void setUserPhoneVerified(Boolean userPhoneVerified) {
        this.userPhoneVerified = userPhoneVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_CREATED_AT
     *
     * @return the value of user.USER_CREATED_AT
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public Date getUserCreatedAt() {
        return userCreatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_CREATED_AT
     *
     * @param userCreatedAt the value for user.USER_CREATED_AT
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public void setUserCreatedAt(Date userCreatedAt) {
        this.userCreatedAt = userCreatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_UPDATED_AT
     *
     * @return the value of user.USER_UPDATED_AT
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public Date getUserUpdatedAt() {
        return userUpdatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_UPDATED_AT
     *
     * @param userUpdatedAt the value for user.USER_UPDATED_AT
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public void setUserUpdatedAt(Date userUpdatedAt) {
        this.userUpdatedAt = userUpdatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_UPDATED_BY
     *
     * @return the value of user.USER_UPDATED_BY
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public Date getUserUpdatedBy() {
        return userUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_UPDATED_BY
     *
     * @param userUpdatedBy the value for user.USER_UPDATED_BY
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public void setUserUpdatedBy(Date userUpdatedBy) {
        this.userUpdatedBy = userUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_LAST_LOGIN_AT
     *
     * @return the value of user.USER_LAST_LOGIN_AT
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public Date getUserLastLoginAt() {
        return userLastLoginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_LAST_LOGIN_AT
     *
     * @param userLastLoginAt the value for user.USER_LAST_LOGIN_AT
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public void setUserLastLoginAt(Date userLastLoginAt) {
        this.userLastLoginAt = userLastLoginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_ACTIVE
     *
     * @return the value of user.USER_ACTIVE
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public Boolean getUserActive() {
        return userActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_ACTIVE
     *
     * @param userActive the value for user.USER_ACTIVE
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    public void setUserActive(Boolean userActive) {
        this.userActive = userActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Jul 18 14:35:37 HKT 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", userEmail=").append(userEmail);
        sb.append(", userEmailVerified=").append(userEmailVerified);
        sb.append(", userPhoneNumber=").append(userPhoneNumber);
        sb.append(", userPhoneVerified=").append(userPhoneVerified);
        sb.append(", userCreatedAt=").append(userCreatedAt);
        sb.append(", userUpdatedAt=").append(userUpdatedAt);
        sb.append(", userUpdatedBy=").append(userUpdatedBy);
        sb.append(", userLastLoginAt=").append(userLastLoginAt);
        sb.append(", userActive=").append(userActive);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}