package com.ecommerce.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    public UserExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("USER_NAME =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("USER_NAME <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("USER_NAME >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NAME >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("USER_NAME <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("USER_NAME <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("USER_NAME like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("USER_NAME not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("USER_NAME in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("USER_NAME not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("USER_NAME between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("USER_NAME not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNull() {
            addCriterion("USER_EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNotNull() {
            addCriterion("USER_EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andUserEmailEqualTo(String value) {
            addCriterion("USER_EMAIL =", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotEqualTo(String value) {
            addCriterion("USER_EMAIL <>", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThan(String value) {
            addCriterion("USER_EMAIL >", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThanOrEqualTo(String value) {
            addCriterion("USER_EMAIL >=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThan(String value) {
            addCriterion("USER_EMAIL <", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThanOrEqualTo(String value) {
            addCriterion("USER_EMAIL <=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLike(String value) {
            addCriterion("USER_EMAIL like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotLike(String value) {
            addCriterion("USER_EMAIL not like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailIn(List<String> values) {
            addCriterion("USER_EMAIL in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotIn(List<String> values) {
            addCriterion("USER_EMAIL not in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailBetween(String value1, String value2) {
            addCriterion("USER_EMAIL between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotBetween(String value1, String value2) {
            addCriterion("USER_EMAIL not between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNumberIsNull() {
            addCriterion("USER_PHONE_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNumberIsNotNull() {
            addCriterion("USER_PHONE_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNumberEqualTo(String value) {
            addCriterion("USER_PHONE_NUMBER =", value, "userPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNumberNotEqualTo(String value) {
            addCriterion("USER_PHONE_NUMBER <>", value, "userPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNumberGreaterThan(String value) {
            addCriterion("USER_PHONE_NUMBER >", value, "userPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("USER_PHONE_NUMBER >=", value, "userPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNumberLessThan(String value) {
            addCriterion("USER_PHONE_NUMBER <", value, "userPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("USER_PHONE_NUMBER <=", value, "userPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNumberLike(String value) {
            addCriterion("USER_PHONE_NUMBER like", value, "userPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNumberNotLike(String value) {
            addCriterion("USER_PHONE_NUMBER not like", value, "userPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNumberIn(List<String> values) {
            addCriterion("USER_PHONE_NUMBER in", values, "userPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNumberNotIn(List<String> values) {
            addCriterion("USER_PHONE_NUMBER not in", values, "userPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNumberBetween(String value1, String value2) {
            addCriterion("USER_PHONE_NUMBER between", value1, value2, "userPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNumberNotBetween(String value1, String value2) {
            addCriterion("USER_PHONE_NUMBER not between", value1, value2, "userPhoneNumber");
            return (Criteria) this;
        }

        public Criteria andUserCreatedAtIsNull() {
            addCriterion("USER_CREATED_AT is null");
            return (Criteria) this;
        }

        public Criteria andUserCreatedAtIsNotNull() {
            addCriterion("USER_CREATED_AT is not null");
            return (Criteria) this;
        }

        public Criteria andUserCreatedAtEqualTo(Date value) {
            addCriterion("USER_CREATED_AT =", value, "userCreatedAt");
            return (Criteria) this;
        }

        public Criteria andUserCreatedAtNotEqualTo(Date value) {
            addCriterion("USER_CREATED_AT <>", value, "userCreatedAt");
            return (Criteria) this;
        }

        public Criteria andUserCreatedAtGreaterThan(Date value) {
            addCriterion("USER_CREATED_AT >", value, "userCreatedAt");
            return (Criteria) this;
        }

        public Criteria andUserCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("USER_CREATED_AT >=", value, "userCreatedAt");
            return (Criteria) this;
        }

        public Criteria andUserCreatedAtLessThan(Date value) {
            addCriterion("USER_CREATED_AT <", value, "userCreatedAt");
            return (Criteria) this;
        }

        public Criteria andUserCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("USER_CREATED_AT <=", value, "userCreatedAt");
            return (Criteria) this;
        }

        public Criteria andUserCreatedAtIn(List<Date> values) {
            addCriterion("USER_CREATED_AT in", values, "userCreatedAt");
            return (Criteria) this;
        }

        public Criteria andUserCreatedAtNotIn(List<Date> values) {
            addCriterion("USER_CREATED_AT not in", values, "userCreatedAt");
            return (Criteria) this;
        }

        public Criteria andUserCreatedAtBetween(Date value1, Date value2) {
            addCriterion("USER_CREATED_AT between", value1, value2, "userCreatedAt");
            return (Criteria) this;
        }

        public Criteria andUserCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("USER_CREATED_AT not between", value1, value2, "userCreatedAt");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedAtIsNull() {
            addCriterion("USER_UPDATED_AT is null");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedAtIsNotNull() {
            addCriterion("USER_UPDATED_AT is not null");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedAtEqualTo(Date value) {
            addCriterion("USER_UPDATED_AT =", value, "userUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedAtNotEqualTo(Date value) {
            addCriterion("USER_UPDATED_AT <>", value, "userUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedAtGreaterThan(Date value) {
            addCriterion("USER_UPDATED_AT >", value, "userUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("USER_UPDATED_AT >=", value, "userUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedAtLessThan(Date value) {
            addCriterion("USER_UPDATED_AT <", value, "userUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("USER_UPDATED_AT <=", value, "userUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedAtIn(List<Date> values) {
            addCriterion("USER_UPDATED_AT in", values, "userUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedAtNotIn(List<Date> values) {
            addCriterion("USER_UPDATED_AT not in", values, "userUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("USER_UPDATED_AT between", value1, value2, "userUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("USER_UPDATED_AT not between", value1, value2, "userUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedByIsNull() {
            addCriterion("USER_UPDATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedByIsNotNull() {
            addCriterion("USER_UPDATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedByEqualTo(Date value) {
            addCriterion("USER_UPDATED_BY =", value, "userUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedByNotEqualTo(Date value) {
            addCriterion("USER_UPDATED_BY <>", value, "userUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedByGreaterThan(Date value) {
            addCriterion("USER_UPDATED_BY >", value, "userUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedByGreaterThanOrEqualTo(Date value) {
            addCriterion("USER_UPDATED_BY >=", value, "userUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedByLessThan(Date value) {
            addCriterion("USER_UPDATED_BY <", value, "userUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedByLessThanOrEqualTo(Date value) {
            addCriterion("USER_UPDATED_BY <=", value, "userUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedByIn(List<Date> values) {
            addCriterion("USER_UPDATED_BY in", values, "userUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedByNotIn(List<Date> values) {
            addCriterion("USER_UPDATED_BY not in", values, "userUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedByBetween(Date value1, Date value2) {
            addCriterion("USER_UPDATED_BY between", value1, value2, "userUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUserUpdatedByNotBetween(Date value1, Date value2) {
            addCriterion("USER_UPDATED_BY not between", value1, value2, "userUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUserLastLoginAtIsNull() {
            addCriterion("USER_LAST_LOGIN_AT is null");
            return (Criteria) this;
        }

        public Criteria andUserLastLoginAtIsNotNull() {
            addCriterion("USER_LAST_LOGIN_AT is not null");
            return (Criteria) this;
        }

        public Criteria andUserLastLoginAtEqualTo(Date value) {
            addCriterion("USER_LAST_LOGIN_AT =", value, "userLastLoginAt");
            return (Criteria) this;
        }

        public Criteria andUserLastLoginAtNotEqualTo(Date value) {
            addCriterion("USER_LAST_LOGIN_AT <>", value, "userLastLoginAt");
            return (Criteria) this;
        }

        public Criteria andUserLastLoginAtGreaterThan(Date value) {
            addCriterion("USER_LAST_LOGIN_AT >", value, "userLastLoginAt");
            return (Criteria) this;
        }

        public Criteria andUserLastLoginAtGreaterThanOrEqualTo(Date value) {
            addCriterion("USER_LAST_LOGIN_AT >=", value, "userLastLoginAt");
            return (Criteria) this;
        }

        public Criteria andUserLastLoginAtLessThan(Date value) {
            addCriterion("USER_LAST_LOGIN_AT <", value, "userLastLoginAt");
            return (Criteria) this;
        }

        public Criteria andUserLastLoginAtLessThanOrEqualTo(Date value) {
            addCriterion("USER_LAST_LOGIN_AT <=", value, "userLastLoginAt");
            return (Criteria) this;
        }

        public Criteria andUserLastLoginAtIn(List<Date> values) {
            addCriterion("USER_LAST_LOGIN_AT in", values, "userLastLoginAt");
            return (Criteria) this;
        }

        public Criteria andUserLastLoginAtNotIn(List<Date> values) {
            addCriterion("USER_LAST_LOGIN_AT not in", values, "userLastLoginAt");
            return (Criteria) this;
        }

        public Criteria andUserLastLoginAtBetween(Date value1, Date value2) {
            addCriterion("USER_LAST_LOGIN_AT between", value1, value2, "userLastLoginAt");
            return (Criteria) this;
        }

        public Criteria andUserLastLoginAtNotBetween(Date value1, Date value2) {
            addCriterion("USER_LAST_LOGIN_AT not between", value1, value2, "userLastLoginAt");
            return (Criteria) this;
        }

        public Criteria andUserActiveIsNull() {
            addCriterion("USER_ACTIVE is null");
            return (Criteria) this;
        }

        public Criteria andUserActiveIsNotNull() {
            addCriterion("USER_ACTIVE is not null");
            return (Criteria) this;
        }

        public Criteria andUserActiveEqualTo(Boolean value) {
            addCriterion("USER_ACTIVE =", value, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveNotEqualTo(Boolean value) {
            addCriterion("USER_ACTIVE <>", value, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveGreaterThan(Boolean value) {
            addCriterion("USER_ACTIVE >", value, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("USER_ACTIVE >=", value, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveLessThan(Boolean value) {
            addCriterion("USER_ACTIVE <", value, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveLessThanOrEqualTo(Boolean value) {
            addCriterion("USER_ACTIVE <=", value, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveIn(List<Boolean> values) {
            addCriterion("USER_ACTIVE in", values, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveNotIn(List<Boolean> values) {
            addCriterion("USER_ACTIVE not in", values, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveBetween(Boolean value1, Boolean value2) {
            addCriterion("USER_ACTIVE between", value1, value2, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("USER_ACTIVE not between", value1, value2, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerifiedIsNull() {
            addCriterion("USER_EMAIL_VERIFIED is null");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerifiedIsNotNull() {
            addCriterion("USER_EMAIL_VERIFIED is not null");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerifiedEqualTo(Boolean value) {
            addCriterion("USER_EMAIL_VERIFIED =", value, "userEmailVerified");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerifiedNotEqualTo(Boolean value) {
            addCriterion("USER_EMAIL_VERIFIED <>", value, "userEmailVerified");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerifiedGreaterThan(Boolean value) {
            addCriterion("USER_EMAIL_VERIFIED >", value, "userEmailVerified");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerifiedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("USER_EMAIL_VERIFIED >=", value, "userEmailVerified");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerifiedLessThan(Boolean value) {
            addCriterion("USER_EMAIL_VERIFIED <", value, "userEmailVerified");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerifiedLessThanOrEqualTo(Boolean value) {
            addCriterion("USER_EMAIL_VERIFIED <=", value, "userEmailVerified");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerifiedIn(List<Boolean> values) {
            addCriterion("USER_EMAIL_VERIFIED in", values, "userEmailVerified");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerifiedNotIn(List<Boolean> values) {
            addCriterion("USER_EMAIL_VERIFIED not in", values, "userEmailVerified");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerifiedBetween(Boolean value1, Boolean value2) {
            addCriterion("USER_EMAIL_VERIFIED between", value1, value2, "userEmailVerified");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerifiedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("USER_EMAIL_VERIFIED not between", value1, value2, "userEmailVerified");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenIsNull() {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN is null");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenIsNotNull() {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN is not null");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenEqualTo(String value) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN =", value, "userEmailVerificationToken");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenNotEqualTo(String value) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN <>", value, "userEmailVerificationToken");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenGreaterThan(String value) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN >", value, "userEmailVerificationToken");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenGreaterThanOrEqualTo(String value) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN >=", value, "userEmailVerificationToken");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenLessThan(String value) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN <", value, "userEmailVerificationToken");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenLessThanOrEqualTo(String value) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN <=", value, "userEmailVerificationToken");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenLike(String value) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN like", value, "userEmailVerificationToken");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenNotLike(String value) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN not like", value, "userEmailVerificationToken");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenIn(List<String> values) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN in", values, "userEmailVerificationToken");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenNotIn(List<String> values) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN not in", values, "userEmailVerificationToken");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenBetween(String value1, String value2) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN between", value1, value2, "userEmailVerificationToken");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenNotBetween(String value1, String value2) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN not between", value1, value2, "userEmailVerificationToken");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenExpiresAtIsNull() {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN_EXPIRES_AT is null");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenExpiresAtIsNotNull() {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN_EXPIRES_AT is not null");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenExpiresAtEqualTo(Date value) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN_EXPIRES_AT =", value, "userEmailVerificationTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenExpiresAtNotEqualTo(Date value) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN_EXPIRES_AT <>", value, "userEmailVerificationTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenExpiresAtGreaterThan(Date value) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN_EXPIRES_AT >", value, "userEmailVerificationTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenExpiresAtGreaterThanOrEqualTo(Date value) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN_EXPIRES_AT >=", value, "userEmailVerificationTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenExpiresAtLessThan(Date value) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN_EXPIRES_AT <", value, "userEmailVerificationTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenExpiresAtLessThanOrEqualTo(Date value) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN_EXPIRES_AT <=", value, "userEmailVerificationTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenExpiresAtIn(List<Date> values) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN_EXPIRES_AT in", values, "userEmailVerificationTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenExpiresAtNotIn(List<Date> values) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN_EXPIRES_AT not in", values, "userEmailVerificationTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenExpiresAtBetween(Date value1, Date value2) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN_EXPIRES_AT between", value1, value2, "userEmailVerificationTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andUserEmailVerificationTokenExpiresAtNotBetween(Date value1, Date value2) {
            addCriterion("USER_EMAIL_VERIFICATION_TOKEN_EXPIRES_AT not between", value1, value2, "userEmailVerificationTokenExpiresAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Sat Jul 26 09:53:37 HKT 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Sat Jul 26 09:53:37 HKT 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}